# Fetching the latest node image on alpine linux
FROM node:alpine

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY ./package.json /app

RUN npm install

# Copying all the files in our project
COPY . .

# Open port
EXPOSE 80
EXPOSE 5000

# Starting our application
CMD ["npm","start"]